# Generated by Django 5.1.4 on 2025-01-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='furniture',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='furniture',
        ),
    ]
