# Generated by Django 5.1.4 on 2025-01-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В обработке', 'В обработке'), ('Отправлен', 'Отправлен'), ('Доставлен', 'Доставлен')], default='Новый', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
