# Generated by Django 5.1.4 on 2025-01-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
