# Generated by Django 5.1.4 on 2025-01-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_promocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
