# Generated by Django 5.1.4 on 2025-01-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет')),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размеры (ДxШxВ)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вес (кг)')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель')),
                ('warranty_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гарантийный срок')),
                ('care_instructions', models.TextField(blank=True, null=True, verbose_name='Инструкции по уходу')),
                ('additional_features', models.TextField(blank=True, null=True, verbose_name='Дополнительные функции')),
                ('furniture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='shop.furniture', verbose_name='Мебель')),
            ],
            options={
                'verbose_name': 'Описание мебели',
                'verbose_name_plural': 'Описание мебели',
            },
        ),
    ]
